name: Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rokit Tools
        run: rokit install

      - name: Install Dependencies
        run: wally install

      - name: Build Model
        run: rojo build -o quickzone.rbxm

      - name: Upload to Roblox
        run: |
          rbxcloud asset upload \
            --asset-id 96553484189609 \
            --filepath quickzone.rbxm \
            --api-key ${{ secrets.ROBLOX_API_KEY }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: quickzone.rbxm
          generate_release_notes: true
